---
title: "p53retriever workflow"
author: "Toma Tebaldi (t.tebaldi@unitn.it)"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{p53retriever workflow}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Info

p53retriever is an R package implementing a pattern search algorithm that maps p53 response elements (REs) and ranks them according to predicted transactivation potentials in five classes. Besides canonical, full site REs, p53retriever contains specific pattern searches for non-canonical half sites and 3/4 sites. REs can be displayed along the input sequence in a graphical layout.

The rules formalized in the model are based on observations obtained during several years of experiments using the yeast-based assays, including the results presented in (Inga et al MCB2002; Tomso et al, PNAS 2005; Jegga et al PNAS 2008; Jordan et al PloS Genetics 2008; Menendez et PNAS 2010).

## Reference

Please cite the following article when using `p53retriever`:

T Tebaldi, S Zaccara, F alessandrini, A Bisio, Y Ciribilli, A Inga. ***Whole-genome cartography of p53 response elements ranked on transactivation potential.*** *BMC Genomics. 2015 Jun 17;16:464*

## Installation

To install `p53retriever`, directly from github: 

    install.packages("devtools")
    library("devtools")
    install_github("tomateba/p53retriever")

## Usage

This code shows how `p53retriever` can be used on the promoter sequence of CDKN1A (-10k, +10k from TSS)

    data(CDKN1A)
    hits<-p53track(CDKN1A,seqname="CDKN1A")
    p53plot(hits,0,20000)



